spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:13306/store?useSSL=false&&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger
      username: user
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 10000
          order_inserts: true
    hibernate:
      ddl-auto: create
    open-in-view: false
