name: CI

on:
  pull_request:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: grant permission    
        run: chmod +x gradlew

      - name: Gradle build
        run: ./gradlew build
